CREATE TABLE cards (
   id BIGSERIAL PRIMARY KEY,
   user_id BIGINT NOT NULL,
   card_number BIGINT NOT NULL,
   card_name VARCHAR(255) NOT NULL,
   status BOOLEAN NOT NULL DEFAULT TRUE,
   card_type VARCHAR(50) NOT NULL,
   CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);